#cloud-config
hostname: mariadb
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOuEu5szJh8sT48W1pQmBlxTV3NGBGyC1WruRkTmQKOT avi@ASIR
chpasswd:
  expire: False
  users:
    - name: ubuntu
      password: asdasd
      type: text
